# Generated by Django 5.2.8 on 2025-11-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='legacy_admin_user', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
