# Generated by Django 4.2.7 on 2023-11-20 18:24
# NOTE: The date in your actual file might be different.

import django.core.validators
from django.db import migrations, models
import django.utils.timezone

# CRITICAL IMPORT: Needed for generating slugs in the data migration
from django.utils.text import slugify


# --- Data Migration Functions ---

def generate_team_slugs(apps, schema_editor):
    """
    Generates a unique slug for every existing Team object based on its name.
    This runs between AddField and AlterField.
    """
    # Replace 'core' with your actual app name if it's different
    Team = apps.get_model('core', 'Team') 
    for team in Team.objects.all():
        base_slug = slugify(team.name)
        slug = base_slug
        counter = 1
        
        # Ensure the generated slug is unique
        while Team.objects.exclude(pk=team.pk).filter(slug=slug).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
            
        team.slug = slug
        team.save()

def reverse_team_slugs(apps, schema_editor):
    """
    Reverse operation (no action needed, as we don't need to undo the slug data).
    """
    pass

# --- End Data Migration Functions ---


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'), # This should be the dependency from your existing file
    ]

    operations = [
        # --- Operations from the previous traceback start here ---

        # 1. Add the slug field temporarily as NOT UNIQUE and NULLABLE
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(max_length=200, unique=False, null=True),
        ),
        
        # 2. RUN PYTHON: Populate the new slug field with unique values for existing rows
        migrations.RunPython(generate_team_slugs, reverse_team_slugs),
        
        # 3. ALTER FIELD: Remove null=True and set unique=True and null=False (non-nullable)
        # This is the final state matching your core/models.py
        migrations.AlterField(
            model_name='team',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, null=False, help_text='A URL-friendly identifier for the team.'),
        ),

        # --- The rest of your existing operations follow ---
        # NOTE: You will likely need to repeat this 3-step process (AddField, RunPython, AlterField)
        # for Sponsor and Tag slugs as well if you encounter those errors next.
        # For this example, I am assuming the rest of your original 0003 migration continues here:
        
        # Example of other operations you may have:
        # migrations.AlterModelOptions(
        #     name='article',
        #     options={'ordering': ['-publish_date'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        # ),
        # ... and so on.

    ]