# Generated by Django 5.2.8 on 2025-11-13 13:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

# CRITICAL FIX: Ensure this is spelled 'slugify', not 'slogify'
from django.utils.text import slugify


# -----------------------------------------------
# --- Data Migration Functions (Must be defined here) ---
# -----------------------------------------------

def generate_sponsor_slugs(apps, schema_editor):
    """Generates a unique slug for every existing Sponsor object based on its name."""
    Sponsor = apps.get_model('core', 'Sponsor') 
    for sponsor in Sponsor.objects.all():
        base_slug = slugify(sponsor.name)
        slug = base_slug
        counter = 1
        
        # Ensure the generated slug is unique
        while Sponsor.objects.exclude(pk=sponsor.pk).filter(slug=slug).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
            
        sponsor.slug = slug
        sponsor.save()

def reverse_sponsor_slugs(apps, schema_editor):
    pass
    
def generate_tag_slugs(apps, schema_editor):
    """Generates a unique slug for every existing Tag object based on its name."""
    Tag = apps.get_model('core', 'Tag') 
    for tag in Tag.objects.all():
        base_slug = slugify(tag.name)
        slug = base_slug
        counter = 1
        
        # Ensure the generated slug is unique
        while Tag.objects.exclude(pk=tag.pk).filter(slug=slug).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
            
        tag.slug = slug
        tag.save()

def reverse_tag_slugs(apps, schema_editor):
    pass

# -----------------------------------------------

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_article_options_alter_faqitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-publish_date'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='faqitem',
            options={'ordering': ['order', 'category', 'question'], 'verbose_name': 'FAQ Item', 'verbose_name_plural': 'FAQ Items'},
        ),
        migrations.AlterModelOptions(
            name='galleryitem',
            options={'ordering': ['-year', 'league', '-created_at'], 'verbose_name': 'Gallery Item', 'verbose_name_plural': 'Gallery Items'},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name': 'Team Registration', 'verbose_name_plural': 'Team Registrations'},
        ),
        migrations.AlterModelOptions(
            name='sponsor',
            options={'ordering': ['tier', 'display_order', 'name'], 'verbose_name': 'Sponsor', 'verbose_name_plural': 'Sponsors'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.RemoveField(
            model_name='galleryitem',
            name='file',
        ),
        migrations.AddField(
            model_name='article',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='article_images/'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO description (max 160 characters).', max_length=160),
        ),
        migrations.AddField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Check to display on the public FAQ page.'),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first.'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='caption',
            field=models.CharField(blank=True, help_text='A short description for the media.', max_length=250),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Upload file for Images.', null=True, upload_to='gallery/images/'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='video_url',
            field=models.URLField(blank=True, help_text='Paste YouTube/Vimeo link for Videos.', max_length=255),
        ),
        migrations.AddField(
            model_name='registration',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text="Reason if the registration status is 'Rejected'."),
        ),
        migrations.AddField(
            model_name='registration',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Manual sort order within a tier.'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only show active sponsors on the website.'),
        ),
        
        # --- SPONSOR SLUG FIX START: Replacing single AddField operation ---
        # 1. Add the slug field temporarily as NOT UNIQUE and NULLABLE
        migrations.AddField(
            model_name='sponsor',
            name='slug',
            field=models.SlugField(max_length=200, unique=False, null=True),
        ),
        # 2. RUN PYTHON: Populate the new slug field with unique values
        migrations.RunPython(generate_sponsor_slugs, reverse_sponsor_slugs),
        # 3. ALTER FIELD: Remove null=True and set unique=True
        migrations.AlterField(
            model_name='sponsor',
            name='slug',
            field=models.SlugField(help_text='Used for sponsor detail URLs (if needed).', max_length=200, unique=True),
        ),
        # --- SPONSOR SLUG FIX END ---
        
        migrations.AddField(
            model_name='sponsor',
            name='website_url',
            field=models.URLField(blank=True, help_text="The sponsor's official website link.", max_length=255),
        ),
        
        # --- TAG SLUG FIX START: Replacing single AddField operation ---
        # 1. Add the slug field temporarily as NOT UNIQUE and NULLABLE
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=50, unique=False, null=True), # Using max_length 50, consistent with Tag fields
        ),
        # 2. RUN PYTHON: Populate the new slug field with unique values
        migrations.RunPython(generate_tag_slugs, reverse_tag_slugs),
        # 3. ALTER FIELD: Remove null=True and set unique=True
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=50, unique=True),
        ),
        # --- TAG SLUG FIX END ---
        
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='team_logos/', verbose_name='Team Logo/Crest'),
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='The other members of the team (excluding the captain).', related_name='team_memberships', to=settings.AUTH_USER_MODEL),
        ),
        
        # --- Remaining AlterFields here ---
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(help_text='A short label used in URLs.', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='core.tag'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated On'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='category',
            field=models.CharField(choices=[('reg', 'Registration'), ('rules', 'Rules & Guidelines'), ('logistics', 'Logistics & Schedule'), ('sponsor', 'Sponsorship'), ('general', 'General')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated On'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='league',
            field=models.CharField(choices=[('techs', 'Techs League'), ('stars', 'Stars League'), ('engineers', 'Engineers League')], db_index=True, max_length=20, verbose_name='League/Category'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image (Upload to file)'), ('video_link', 'Video (External URL)')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated On'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='year',
            field=models.PositiveSmallIntegerField(help_text='The year the media was taken.', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2027)]),
        ),
        migrations.AlterField(
            model_name='registration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='documents',
            field=models.FileField(help_text='Upload official registration documents.', upload_to='registrations/'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='core.team'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated On'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='tier',
            field=models.CharField(choices=[('platinum', 'Platinum'), ('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated On'),
        ),
        migrations.AlterField(
            model_name='team',
            name='captain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captain_of_teams', to=settings.AUTH_USER_MODEL, verbose_name='Team Captain'),
        ),
        migrations.AlterField(
            model_name='team',
            name='category',
            field=models.CharField(choices=[('techs', 'Techs League'), ('stars', 'Stars League'), ('engineers', 'Engineers League')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated On'),
        ),
    ]